import React, { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  tr: {
    // Navigation
    dashboard: 'Kontrol Paneli',
    leads: 'Müşteriler',
    findLeads: 'Müşteri Bul',
    orders: 'Siparişler',
    shipments: 'Kargo Takip',
    products: 'Ürünler',
    productVideos: 'Ürün Videoları',
    specifications: 'Spesifikasyonlar',
    recipes: 'Reçeteler',
    routePlanner: 'Rota Planlayıcı',
    dailyReports: 'Günlük Raporlar',
    templates: 'Şablonlar',
    mailInbox: 'Gelen Kutusu',
    emailComposer: 'Mail Oluştur',
    emailHistory: 'Mail Geçmişi',
    settings: 'Ayarlar',
    language: 'Dil',
    
    // Dashboard
    totalLeads: 'Toplam Müşteri',
    totalOrders: 'Toplam Sipariş',
    emailsSent: 'Gönderilen Mail',
    emailsFailed: 'Başarısız Mail',
    recentLeads: 'Son Eklenen Müşteriler',
    noLeadsYet: 'Henüz müşteri yok',
    recentShipments: 'Son Kargolar',
    
    // Leads
    addLead: 'Müşteri Ekle',
    editLead: 'Müşteri Düzenle',
    deleteLead: 'Müşteri Sil',
    firstName: 'Ad',
    lastName: 'Soyad',
    companyName: 'Firma Adı',
    taxNumber: 'Vergi Numarası',
    address: 'Adres',
    email: 'E-posta',
    phone: 'Telefon',
    city: 'Şehir',
    country: 'Ülke',
    notes: 'Notlar',
    actions: 'İşlemler',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    sendEmail: 'Mail Gönder',
    confirmDelete: 'Bu öğeyi silmek istediğinize emin misiniz?',
    
    // Products & Videos
    uploadVideo: 'Video Yükle',
    dragDropVideo: 'Videoyu buraya sürükleyin veya tıklayın',
    sendViaWhatsApp: 'WhatsApp ile Gönder',
    sendViaEmail: 'Mail ile Gönder',
    productVideo: 'Ürün Videosu',
    videoTitle: 'Video Başlığı',
    videoDescription: 'Açıklama',
    noVideos: 'Henüz video yok',
    
    // Mail Inbox
    inbox: 'Gelen Kutusu',
    sent: 'Gönderilenler',
    drafts: 'Taslaklar',
    compose: 'Yeni Mail',
    from: 'Kimden',
    to: 'Kime',
    subject: 'Konu',
    date: 'Tarih',
    noEmails: 'Henüz mail yok',
    reply: 'Yanıtla',
    forward: 'İlet',
    markAsRead: 'Okundu İşaretle',
    markAsUnread: 'Okunmadı İşaretle',
    refresh: 'Yenile',
    
    // Templates
    addTemplate: 'Şablon Ekle',
    templateName: 'Şablon Adı',
    body: 'İçerik',
    noTemplates: 'Henüz şablon yok',
    
    // Email Composer
    selectLead: 'Müşteri Seç',
    generateWithAI: 'AI ile Oluştur',
    generating: 'Oluşturuluyor...',
    send: 'Gönder',
    preview: 'Önizleme',
    emailSubject: 'Mail Konusu',
    emailBody: 'Mail İçeriği',
    tone: 'Ton',
    professional: 'Profesyonel',
    friendly: 'Samimi',
    formal: 'Resmi',
    
    // Email History
    recipient: 'Alıcı',
    company: 'Firma',
    status: 'Durum',
    sentAt: 'Gönderim Zamanı',
    failed: 'Başarısız',
    noEmailHistory: 'Henüz mail geçmişi yok',
    
    // Settings
    smtpSettings: 'SMTP Ayarları',
    imapSettings: 'IMAP Ayarları',
    smtpHost: 'SMTP Sunucusu',
    imapHost: 'IMAP Sunucusu',
    smtpPort: 'SMTP Port',
    imapPort: 'IMAP Port',
    smtpUsername: 'Kullanıcı Adı',
    smtpPassword: 'Şifre',
    fromEmail: 'Gönderen E-posta',
    fromName: 'Gönderen Adı',
    useTLS: 'TLS Kullan',
    useSSL: 'SSL Kullan',
    testConnection: 'Bağlantıyı Test Et',
    saveSettings: 'Ayarları Kaydet',
    
    // Orders
    order: 'Sipariş',
    orderDate: 'Sipariş Tarihi',
    quantity: 'Miktar',
    unitPrice: 'Birim Fiyat',
    pending: 'Beklemede',
    confirmed: 'Onaylandı',
    shipped: 'Gönderildi',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal',
    
    // Shipments
    trackingNumber: 'Takip Numarası',
    carrier: 'Kargo Firması',
    shipmentStatus: 'Kargo Durumu',
    
    // Messages
    leadAdded: 'Müşteri eklendi',
    leadUpdated: 'Müşteri güncellendi',
    leadDeleted: 'Müşteri silindi',
    templateAdded: 'Şablon eklendi',
    templateDeleted: 'Şablon silindi',
    emailSent: 'Mail gönderildi',
    emailQueued: 'Mail kuyruğa eklendi',
    settingsSaved: 'Ayarlar kaydedildi',
    connectionSuccess: 'Bağlantı başarılı',
    connectionFailed: 'Bağlantı başarısız',
    error: 'Hata',
    success: 'Başarılı',
    loading: 'Yükleniyor...',
    search: 'Ara',
    noResults: 'Sonuç bulunamadı',
    
    // Common
    all: 'Tümü',
    today: 'Bugün',
    yesterday: 'Dün',
    thisWeek: 'Bu Hafta',
    thisMonth: 'Bu Ay',
    download: 'İndir',
    upload: 'Yükle',
    share: 'Paylaş',
    view: 'Görüntüle',
    close: 'Kapat',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    selectAll: 'Tümünü Seç',
    deselectAll: 'Seçimi Kaldır',
  },
  de: {
    // Navigation
    dashboard: 'Dashboard',
    leads: 'Kunden',
    findLeads: 'Kunden finden',
    orders: 'Bestellungen',
    shipments: 'Sendungsverfolgung',
    products: 'Produkte',
    productVideos: 'Produktvideos',
    specifications: 'Spezifikationen',
    recipes: 'Rezepte',
    routePlanner: 'Routenplaner',
    dailyReports: 'Tagesberichte',
    templates: 'Vorlagen',
    mailInbox: 'Posteingang',
    emailComposer: 'E-Mail erstellen',
    emailHistory: 'E-Mail-Verlauf',
    settings: 'Einstellungen',
    language: 'Sprache',
    
    // Dashboard
    totalLeads: 'Gesamtkunden',
    totalOrders: 'Gesamtbestellungen',
    emailsSent: 'Gesendete E-Mails',
    emailsFailed: 'Fehlgeschlagene E-Mails',
    recentLeads: 'Neueste Kunden',
    noLeadsYet: 'Noch keine Kunden',
    recentShipments: 'Letzte Sendungen',
    
    // Leads
    addLead: 'Kunde hinzufügen',
    editLead: 'Kunde bearbeiten',
    deleteLead: 'Kunde löschen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    companyName: 'Firmenname',
    taxNumber: 'Steuernummer',
    address: 'Adresse',
    email: 'E-Mail',
    phone: 'Telefon',
    city: 'Stadt',
    country: 'Land',
    notes: 'Notizen',
    actions: 'Aktionen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    sendEmail: 'E-Mail senden',
    confirmDelete: 'Möchten Sie dieses Element wirklich löschen?',
    
    // Products & Videos
    uploadVideo: 'Video hochladen',
    dragDropVideo: 'Video hierher ziehen oder klicken',
    sendViaWhatsApp: 'Per WhatsApp senden',
    sendViaEmail: 'Per E-Mail senden',
    productVideo: 'Produktvideo',
    videoTitle: 'Videotitel',
    videoDescription: 'Beschreibung',
    noVideos: 'Noch keine Videos',
    
    // Mail Inbox
    inbox: 'Posteingang',
    sent: 'Gesendet',
    drafts: 'Entwürfe',
    compose: 'Neue E-Mail',
    from: 'Von',
    to: 'An',
    subject: 'Betreff',
    date: 'Datum',
    noEmails: 'Noch keine E-Mails',
    reply: 'Antworten',
    forward: 'Weiterleiten',
    markAsRead: 'Als gelesen markieren',
    markAsUnread: 'Als ungelesen markieren',
    refresh: 'Aktualisieren',
    
    // Templates
    addTemplate: 'Vorlage hinzufügen',
    templateName: 'Vorlagenname',
    body: 'Inhalt',
    noTemplates: 'Noch keine Vorlagen',
    
    // Email Composer
    selectLead: 'Kunde auswählen',
    generateWithAI: 'Mit KI erstellen',
    generating: 'Wird erstellt...',
    send: 'Senden',
    preview: 'Vorschau',
    emailSubject: 'E-Mail-Betreff',
    emailBody: 'E-Mail-Inhalt',
    tone: 'Ton',
    professional: 'Professionell',
    friendly: 'Freundlich',
    formal: 'Formell',
    
    // Email History
    recipient: 'Empfänger',
    company: 'Firma',
    status: 'Status',
    sentAt: 'Gesendet am',
    failed: 'Fehlgeschlagen',
    noEmailHistory: 'Noch kein E-Mail-Verlauf',
    
    // Settings
    smtpSettings: 'SMTP-Einstellungen',
    imapSettings: 'IMAP-Einstellungen',
    smtpHost: 'SMTP-Server',
    imapHost: 'IMAP-Server',
    smtpPort: 'SMTP-Port',
    imapPort: 'IMAP-Port',
    smtpUsername: 'Benutzername',
    smtpPassword: 'Passwort',
    fromEmail: 'Absender-E-Mail',
    fromName: 'Absendername',
    useTLS: 'TLS verwenden',
    useSSL: 'SSL verwenden',
    testConnection: 'Verbindung testen',
    saveSettings: 'Einstellungen speichern',
    
    // Orders
    order: 'Bestellung',
    orderDate: 'Bestelldatum',
    quantity: 'Menge',
    unitPrice: 'Stückpreis',
    pending: 'Ausstehend',
    confirmed: 'Bestätigt',
    shipped: 'Versendet',
    delivered: 'Geliefert',
    cancelled: 'Storniert',
    
    // Shipments
    trackingNumber: 'Sendungsnummer',
    carrier: 'Spediteur',
    shipmentStatus: 'Sendungsstatus',
    
    // Messages
    leadAdded: 'Kunde hinzugefügt',
    leadUpdated: 'Kunde aktualisiert',
    leadDeleted: 'Kunde gelöscht',
    templateAdded: 'Vorlage hinzugefügt',
    templateDeleted: 'Vorlage gelöscht',
    emailSent: 'E-Mail gesendet',
    emailQueued: 'E-Mail in Warteschlange',
    settingsSaved: 'Einstellungen gespeichert',
    connectionSuccess: 'Verbindung erfolgreich',
    connectionFailed: 'Verbindung fehlgeschlagen',
    error: 'Fehler',
    success: 'Erfolg',
    loading: 'Wird geladen...',
    search: 'Suchen',
    noResults: 'Keine Ergebnisse',
    
    // Common
    all: 'Alle',
    today: 'Heute',
    yesterday: 'Gestern',
    thisWeek: 'Diese Woche',
    thisMonth: 'Diesen Monat',
    download: 'Herunterladen',
    upload: 'Hochladen',
    share: 'Teilen',
    view: 'Ansehen',
    close: 'Schließen',
    back: 'Zurück',
    next: 'Weiter',
    previous: 'Vorherige',
    selectAll: 'Alle auswählen',
    deselectAll: 'Auswahl aufheben',
  },
  en: {
    // Navigation
    dashboard: 'Dashboard',
    leads: 'Leads',
    findLeads: 'Find Leads',
    orders: 'Orders',
    shipments: 'Shipments',
    products: 'Products',
    productVideos: 'Product Videos',
    specifications: 'Specifications',
    recipes: 'Recipes',
    routePlanner: 'Route Planner',
    dailyReports: 'Daily Reports',
    templates: 'Templates',
    mailInbox: 'Mail Inbox',
    emailComposer: 'Compose Email',
    emailHistory: 'Email History',
    settings: 'Settings',
    language: 'Language',
    
    // Dashboard
    totalLeads: 'Total Leads',
    totalOrders: 'Total Orders',
    emailsSent: 'Emails Sent',
    emailsFailed: 'Failed Emails',
    recentLeads: 'Recent Leads',
    noLeadsYet: 'No leads yet',
    recentShipments: 'Recent Shipments',
    
    // Leads
    addLead: 'Add Lead',
    editLead: 'Edit Lead',
    deleteLead: 'Delete Lead',
    firstName: 'First Name',
    lastName: 'Last Name',
    companyName: 'Company Name',
    taxNumber: 'Tax Number',
    address: 'Address',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    country: 'Country',
    notes: 'Notes',
    actions: 'Actions',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    sendEmail: 'Send Email',
    confirmDelete: 'Are you sure you want to delete this item?',
    
    // Products & Videos
    uploadVideo: 'Upload Video',
    dragDropVideo: 'Drag and drop video here or click',
    sendViaWhatsApp: 'Send via WhatsApp',
    sendViaEmail: 'Send via Email',
    productVideo: 'Product Video',
    videoTitle: 'Video Title',
    videoDescription: 'Description',
    noVideos: 'No videos yet',
    
    // Mail Inbox
    inbox: 'Inbox',
    sent: 'Sent',
    drafts: 'Drafts',
    compose: 'Compose',
    from: 'From',
    to: 'To',
    subject: 'Subject',
    date: 'Date',
    noEmails: 'No emails yet',
    reply: 'Reply',
    forward: 'Forward',
    markAsRead: 'Mark as Read',
    markAsUnread: 'Mark as Unread',
    refresh: 'Refresh',
    
    // Templates
    addTemplate: 'Add Template',
    templateName: 'Template Name',
    body: 'Body',
    noTemplates: 'No templates yet',
    
    // Email Composer
    selectLead: 'Select Lead',
    generateWithAI: 'Generate with AI',
    generating: 'Generating...',
    send: 'Send',
    preview: 'Preview',
    emailSubject: 'Email Subject',
    emailBody: 'Email Body',
    tone: 'Tone',
    professional: 'Professional',
    friendly: 'Friendly',
    formal: 'Formal',
    
    // Email History
    recipient: 'Recipient',
    company: 'Company',
    status: 'Status',
    sentAt: 'Sent At',
    failed: 'Failed',
    noEmailHistory: 'No email history yet',
    
    // Settings
    smtpSettings: 'SMTP Settings',
    imapSettings: 'IMAP Settings',
    smtpHost: 'SMTP Host',
    imapHost: 'IMAP Host',
    smtpPort: 'SMTP Port',
    imapPort: 'IMAP Port',
    smtpUsername: 'Username',
    smtpPassword: 'Password',
    fromEmail: 'From Email',
    fromName: 'From Name',
    useTLS: 'Use TLS',
    useSSL: 'Use SSL',
    testConnection: 'Test Connection',
    saveSettings: 'Save Settings',
    
    // Orders
    order: 'Order',
    orderDate: 'Order Date',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    pending: 'Pending',
    confirmed: 'Confirmed',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    
    // Shipments
    trackingNumber: 'Tracking Number',
    carrier: 'Carrier',
    shipmentStatus: 'Shipment Status',
    
    // Messages
    leadAdded: 'Lead added',
    leadUpdated: 'Lead updated',
    leadDeleted: 'Lead deleted',
    templateAdded: 'Template added',
    templateDeleted: 'Template deleted',
    emailSent: 'Email sent',
    emailQueued: 'Email queued',
    settingsSaved: 'Settings saved',
    connectionSuccess: 'Connection successful',
    connectionFailed: 'Connection failed',
    error: 'Error',
    success: 'Success',
    loading: 'Loading...',
    search: 'Search',
    noResults: 'No results found',
    
    // Common
    all: 'All',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    download: 'Download',
    upload: 'Upload',
    share: 'Share',
    view: 'View',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
  },
  pl: {
    // Navigation - Polish
    dashboard: 'Panel sterowania',
    leads: 'Klienci',
    findLeads: 'Znajdź klientów',
    orders: 'Zamówienia',
    shipments: 'Śledzenie przesyłek',
    products: 'Produkty',
    productVideos: 'Filmy produktowe',
    specifications: 'Specyfikacje',
    recipes: 'Receptury',
    routePlanner: 'Planowanie trasy',
    dailyReports: 'Raporty dzienne',
    templates: 'Szablony',
    mailInbox: 'Skrzynka odbiorcza',
    emailComposer: 'Napisz e-mail',
    emailHistory: 'Historia e-mail',
    settings: 'Ustawienia',
    language: 'Język',
    
    // Dashboard
    totalLeads: 'Łączna liczba klientów',
    totalOrders: 'Łączna liczba zamówień',
    emailsSent: 'Wysłane e-maile',
    emailsFailed: 'Nieudane e-maile',
    recentLeads: 'Ostatnio dodani klienci',
    noLeadsYet: 'Brak klientów',
    recentShipments: 'Ostatnie przesyłki',
    
    // Leads
    addLead: 'Dodaj klienta',
    editLead: 'Edytuj klienta',
    deleteLead: 'Usuń klienta',
    firstName: 'Imię',
    lastName: 'Nazwisko',
    companyName: 'Nazwa firmy',
    taxNumber: 'NIP',
    address: 'Adres',
    email: 'E-mail',
    phone: 'Telefon',
    city: 'Miasto',
    country: 'Kraj',
    notes: 'Notatki',
    actions: 'Akcje',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    sendEmail: 'Wyślij e-mail',
    confirmDelete: 'Czy na pewno chcesz usunąć ten element?',
    
    // Products & Videos
    uploadVideo: 'Prześlij wideo',
    dragDropVideo: 'Przeciągnij i upuść wideo tutaj lub kliknij',
    sendViaWhatsApp: 'Wyślij przez WhatsApp',
    sendViaEmail: 'Wyślij e-mailem',
    productVideo: 'Film produktowy',
    videoTitle: 'Tytuł wideo',
    videoDescription: 'Opis',
    noVideos: 'Brak filmów',
    
    // Mail Inbox
    inbox: 'Skrzynka odbiorcza',
    sent: 'Wysłane',
    drafts: 'Szkice',
    compose: 'Nowy e-mail',
    from: 'Od',
    to: 'Do',
    subject: 'Temat',
    date: 'Data',
    noEmails: 'Brak e-maili',
    reply: 'Odpowiedz',
    forward: 'Przekaż',
    markAsRead: 'Oznacz jako przeczytane',
    markAsUnread: 'Oznacz jako nieprzeczytane',
    refresh: 'Odśwież',
    
    // Templates
    addTemplate: 'Dodaj szablon',
    templateName: 'Nazwa szablonu',
    body: 'Treść',
    noTemplates: 'Brak szablonów',
    
    // Email Composer
    selectLead: 'Wybierz klienta',
    generateWithAI: 'Generuj z AI',
    generating: 'Generowanie...',
    send: 'Wyślij',
    preview: 'Podgląd',
    emailSubject: 'Temat e-mail',
    emailBody: 'Treść e-mail',
    tone: 'Ton',
    professional: 'Profesjonalny',
    friendly: 'Przyjazny',
    formal: 'Formalny',
    
    // Email History
    recipient: 'Odbiorca',
    company: 'Firma',
    status: 'Status',
    sentAt: 'Wysłano',
    failed: 'Nieudane',
    noEmailHistory: 'Brak historii e-mail',
    
    // Settings
    smtpSettings: 'Ustawienia SMTP',
    imapSettings: 'Ustawienia IMAP',
    smtpHost: 'Serwer SMTP',
    imapHost: 'Serwer IMAP',
    smtpPort: 'Port SMTP',
    imapPort: 'Port IMAP',
    smtpUsername: 'Nazwa użytkownika',
    smtpPassword: 'Hasło',
    fromEmail: 'E-mail nadawcy',
    fromName: 'Nazwa nadawcy',
    useTLS: 'Użyj TLS',
    useSSL: 'Użyj SSL',
    testConnection: 'Testuj połączenie',
    saveSettings: 'Zapisz ustawienia',
    
    // Orders
    order: 'Zamówienie',
    orderDate: 'Data zamówienia',
    quantity: 'Ilość',
    unitPrice: 'Cena jednostkowa',
    pending: 'Oczekujące',
    confirmed: 'Potwierdzone',
    shipped: 'Wysłane',
    delivered: 'Dostarczone',
    cancelled: 'Anulowane',
    
    // Shipments
    trackingNumber: 'Numer śledzenia',
    carrier: 'Przewoźnik',
    shipmentStatus: 'Status przesyłki',
    
    // Messages
    leadAdded: 'Klient dodany',
    leadUpdated: 'Klient zaktualizowany',
    leadDeleted: 'Klient usunięty',
    templateAdded: 'Szablon dodany',
    templateDeleted: 'Szablon usunięty',
    emailSent: 'E-mail wysłany',
    emailQueued: 'E-mail w kolejce',
    settingsSaved: 'Ustawienia zapisane',
    connectionSuccess: 'Połączenie udane',
    connectionFailed: 'Połączenie nieudane',
    error: 'Błąd',
    success: 'Sukces',
    loading: 'Ładowanie...',
    search: 'Szukaj',
    noResults: 'Brak wyników',
    
    // Common
    all: 'Wszystko',
    today: 'Dziś',
    yesterday: 'Wczoraj',
    thisWeek: 'Ten tydzień',
    thisMonth: 'Ten miesiąc',
    download: 'Pobierz',
    upload: 'Prześlij',
    share: 'Udostępnij',
    view: 'Zobacz',
    close: 'Zamknij',
    back: 'Wstecz',
    next: 'Dalej',
    previous: 'Poprzedni',
    selectAll: 'Zaznacz wszystko',
    deselectAll: 'Odznacz wszystko',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('tr'); // Default to Turkish
  
  const t = useCallback((key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  }, [language]);
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
